export const CYBER_DIFFICULTY = {
  EASY: 'easy',
  MEDIUM: 'medium',
  HARD: 'hard',
}

export const ctfChallenges = [
  // Web Security
  {
    id: 'web-001',
    title: 'Cookie Monster',
    category: 'Web',
    difficulty: CYBER_DIFFICULTY.EASY,
    points: 100,
    estimatedMinutes: 20,
    tags: ['cookies', 'auth', 'logic'],
    shortDescription: 'Найдите способ получить роль admin, не имея пароля.',
    story: 'В учебном приложении доступ к панели даётся по cookie role. Что может пойти не так?',
    objective: 'Получить доступ к admin-панели.',
    hint: 'Посмотрите внимательно, что хранится в cookie/localStorage.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{COOKIE_TRUST_IS_BAD}',
  },
  {
    id: 'web-002',
    title: 'SQL Injection Basics',
    category: 'Web',
    difficulty: CYBER_DIFFICULTY.EASY,
    points: 150,
    estimatedMinutes: 25,
    tags: ['sql', 'injection', 'database'],
    shortDescription: 'Классическая SQL-инъекция в форме поиска пользователей.',
    story: 'Администратор забыл использовать prepared statements. Найдите способ извлечь данные.',
    objective: 'Извлечь пароль администратора из базы данных.',
    hint: 'Попробуйте UNION SELECT или комментарии SQL.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{SQL_INJECTION_101}',
  },
  {
    id: 'web-003',
    title: 'XSS Reflected',
    category: 'Web',
    difficulty: CYBER_DIFFICULTY.MEDIUM,
    points: 200,
    estimatedMinutes: 30,
    tags: ['xss', 'reflected', 'javascript'],
    shortDescription: 'Отражённая XSS-атака через параметр URL.',
    story: 'Поисковая форма не фильтрует пользовательский ввод. Внедрите скрипт.',
    objective: 'Выполнить JavaScript в контексте жертвы.',
    hint: 'Попробуйте <script> или события onerror/onload.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{XSS_REFLECTED_SUCCESS}',
  },
  {
    id: 'web-004',
    title: 'CSRF Token Bypass',
    category: 'Web',
    difficulty: CYBER_DIFFICULTY.MEDIUM,
    points: 250,
    estimatedMinutes: 35,
    tags: ['csrf', 'token', 'bypass'],
    shortDescription: 'Обход CSRF-токена через слабую валидацию.',
    story: 'Приложение использует CSRF-токены, но проверка реализована некорректно.',
    objective: 'Выполнить действие от имени другого пользователя.',
    hint: 'Проверьте, как валидируется токен и можно ли его предсказать.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{CSRF_WEAK_VALIDATION}',
  },
  {
    id: 'web-005',
    title: 'JWT Secret Brute Force',
    category: 'Web',
    difficulty: CYBER_DIFFICULTY.HARD,
    points: 400,
    estimatedMinutes: 50,
    tags: ['jwt', 'bruteforce', 'crypto'],
    shortDescription: 'Взлом JWT-токена через слабый секретный ключ.',
    story: 'Сервер использует JWT для аутентификации, но секрет слишком простой.',
    objective: 'Подделать JWT-токен и получить доступ к защищённому ресурсу.',
    hint: 'Попробуйте словарь популярных секретов или частотный анализ.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{JWT_WEAK_SECRET}',
  },
  {
    id: 'web-006',
    title: 'File Upload Bypass',
    category: 'Web',
    difficulty: CYBER_DIFFICULTY.MEDIUM,
    points: 300,
    estimatedMinutes: 40,
    tags: ['upload', 'bypass', 'rce'],
    shortDescription: 'Обход ограничений загрузки файлов для выполнения кода.',
    story: 'Система проверяет расширение файла, но не содержимое.',
    objective: 'Загрузить и выполнить PHP-шелл на сервере.',
    hint: 'Попробуйте двойные расширения, null-байты или MIME-типы.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{FILE_UPLOAD_BYPASS}',
  },
  {
    id: 'web-007',
    title: 'IDOR Vulnerability',
    category: 'Web',
    difficulty: CYBER_DIFFICULTY.EASY,
    points: 120,
    estimatedMinutes: 15,
    tags: ['idor', 'authorization', 'access'],
    shortDescription: 'Небезопасная прямая ссылка на объект (IDOR).',
    story: 'API не проверяет права доступа при запросе ресурса по ID.',
    objective: 'Получить доступ к данным другого пользователя.',
    hint: 'Попробуйте изменить ID в URL или параметрах запроса.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{IDOR_EXPLOITED}',
  },
  {
    id: 'web-008',
    title: 'XXE Injection',
    category: 'Web',
    difficulty: CYBER_DIFFICULTY.HARD,
    points: 450,
    estimatedMinutes: 55,
    tags: ['xxe', 'xml', 'injection'],
    shortDescription: 'XML External Entity (XXE) инъекция для чтения файлов.',
    story: 'Приложение парсит XML без отключения внешних сущностей.',
    objective: 'Прочитать конфиденциальный файл с сервера через XXE.',
    hint: 'Используйте SYSTEM и ENTITY для чтения файлов.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{XXE_FILE_READ}',
  },

  // Cryptography
  {
    id: 'crypto-001',
    title: 'XOR Party',
    category: 'Crypto',
    difficulty: CYBER_DIFFICULTY.MEDIUM,
    points: 220,
    estimatedMinutes: 40,
    tags: ['xor', 'encoding'],
    shortDescription: 'Дешифруйте сообщение, зашифрованное слабым XOR.',
    story: 'Разработчик "ускорил" шифрование XOR-ом. Теперь вы ускорьте взлом.',
    objective: 'Расшифровать сообщение и получить флаг.',
    hint: 'Один ключ на всё сообщение — плохая идея.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{XOR_IS_NOT_ENCRYPTION}',
  },
  {
    id: 'crypto-002',
    title: 'RSA Small Exponent',
    category: 'Crypto',
    difficulty: CYBER_DIFFICULTY.MEDIUM,
    points: 280,
    estimatedMinutes: 45,
    tags: ['rsa', 'small-exponent', 'math'],
    shortDescription: 'Атака на RSA с маленьким публичным экспонентом.',
    story: 'Сервер использует e=3 для RSA. Найдите способ расшифровать сообщение.',
    objective: 'Восстановить исходное сообщение из зашифрованного.',
    hint: 'При e=3 можно использовать кубический корень, если m^3 < n.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{RSA_SMALL_E}',
  },
  {
    id: 'crypto-003',
    title: 'Caesar Cipher',
    category: 'Crypto',
    difficulty: CYBER_DIFFICULTY.EASY,
    points: 80,
    estimatedMinutes: 10,
    tags: ['caesar', 'substitution', 'classic'],
    shortDescription: 'Классический шифр Цезаря с неизвестным сдвигом.',
    story: 'Сообщение зашифровано шифром Цезаря. Найдите правильный сдвиг.',
    objective: 'Расшифровать сообщение методом перебора.',
    hint: 'Всего 25 возможных сдвигов для английского алфавита.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{CAESAR_SHIFT_13}',
  },
  {
    id: 'crypto-004',
    title: 'Hash Collision',
    category: 'Crypto',
    difficulty: CYBER_DIFFICULTY.HARD,
    points: 500,
    estimatedMinutes: 60,
    tags: ['hash', 'collision', 'md5'],
    shortDescription: 'Найдите коллизию MD5 для обхода проверки.',
    story: 'Система проверяет целостность файла через MD5. Найдите коллизию.',
    objective: 'Создать два файла с одинаковым MD5, но разным содержимым.',
    hint: 'MD5 уязвим к коллизиям. Используйте известные пары коллизий.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{MD5_COLLISION_FOUND}',
  },
  {
    id: 'crypto-005',
    title: 'AES ECB Weakness',
    category: 'Crypto',
    difficulty: CYBER_DIFFICULTY.MEDIUM,
    points: 320,
    estimatedMinutes: 50,
    tags: ['aes', 'ecb', 'block-cipher'],
    shortDescription: 'Эксплуатация слабости режима ECB в AES.',
    story: 'Приложение использует AES-ECB для шифрования. Найдите паттерны.',
    objective: 'Расшифровать сообщение, используя особенности ECB.',
    hint: 'ECB шифрует блоки независимо. Одинаковые блоки дают одинаковый шифротекст.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{AES_ECB_PATTERN}',
  },

  // Forensics
  {
    id: 'for-001',
    title: 'Log Sleuth',
    category: 'Forensics',
    difficulty: CYBER_DIFFICULTY.EASY,
    points: 120,
    estimatedMinutes: 25,
    tags: ['logs', 'analysis'],
    shortDescription: 'В логах спрятан ключ доступа. Найдите подозрительную строку.',
    story: 'Команда оставила дебаг-лог в проде. В нём случайно утёк токен.',
    objective: 'Найти утёкший токен и подтвердить флаг.',
    hint: 'Ищите строки со словами token/secret/key.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{NEVER_LOG_SECRETS}',
  },
  {
    id: 'for-002',
    title: 'PCAP Analysis',
    category: 'Forensics',
    difficulty: CYBER_DIFFICULTY.MEDIUM,
    points: 250,
    estimatedMinutes: 40,
    tags: ['pcap', 'wireshark', 'network'],
    shortDescription: 'Анализ сетевого трафика для поиска утёкших данных.',
    story: 'В сетевом дампе зафиксирована передача конфиденциальных данных.',
    objective: 'Найти и извлечь секретный ключ из трафика.',
    hint: 'Используйте Wireshark для фильтрации HTTP/FTP трафика.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{PCAP_ANALYSIS_DONE}',
  },
  {
    id: 'for-003',
    title: 'Memory Dump',
    category: 'Forensics',
    difficulty: CYBER_DIFFICULTY.HARD,
    points: 400,
    estimatedMinutes: 55,
    tags: ['memory', 'dump', 'volatility'],
    shortDescription: 'Анализ дампа памяти для поиска паролей и ключей.',
    story: 'Получен дамп памяти скомпрометированной системы. Найдите секреты.',
    objective: 'Извлечь пароли и ключи из дампа памяти.',
    hint: 'Используйте Volatility Framework для анализа дампа.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{MEMORY_DUMP_ANALYSIS}',
  },
  {
    id: 'for-004',
    title: 'Deleted File Recovery',
    category: 'Forensics',
    difficulty: CYBER_DIFFICULTY.MEDIUM,
    points: 280,
    estimatedMinutes: 45,
    tags: ['recovery', 'deleted', 'filesystem'],
    shortDescription: 'Восстановление удалённого файла с флагом.',
    story: 'Файл был удалён, но данные могут остаться на диске.',
    objective: 'Восстановить удалённый файл и извлечь флаг.',
    hint: 'Используйте инструменты для восстановления файлов (testdisk, photorec).',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{DELETED_FILE_RECOVERED}',
  },
  {
    id: 'for-005',
    title: 'Steganography Hidden',
    category: 'Forensics',
    difficulty: CYBER_DIFFICULTY.MEDIUM,
    points: 300,
    estimatedMinutes: 50,
    tags: ['steganography', 'image', 'hidden'],
    shortDescription: 'Найдите скрытое сообщение в изображении.',
    story: 'В изображении спрятано секретное сообщение методом стеганографии.',
    objective: 'Извлечь скрытое сообщение из изображения.',
    hint: 'Попробуйте LSB-анализ, EXIF-данные или инструменты вроде steghide.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{STEGANOGRAPHY_FOUND}',
  },

  // OSINT
  {
    id: 'osint-001',
    title: 'Public Footprint',
    category: 'OSINT',
    difficulty: CYBER_DIFFICULTY.MEDIUM,
    points: 200,
    estimatedMinutes: 35,
    tags: ['osint', 'metadata', 'search'],
    shortDescription: 'Соберите публичный след и найдите "ключ" в метаданных.',
    story: 'Изображение "вроде обычное", но метаданные расскажут больше.',
    objective: 'Извлечь ключ из метаданных.',
    hint: 'EXIF тоже считается.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{METADATA_MATTERS}',
  },
  {
    id: 'osint-002',
    title: 'Social Media Recon',
    category: 'OSINT',
    difficulty: CYBER_DIFFICULTY.MEDIUM,
    points: 250,
    estimatedMinutes: 40,
    tags: ['osint', 'social', 'recon'],
    shortDescription: 'Соберите информацию о цели из социальных сетей.',
    story: 'Нужно найти публичную информацию о человеке через соцсети.',
    objective: 'Найти скрытую информацию и составить профиль цели.',
    hint: 'Проверьте публичные профили, посты, геолокацию, друзей.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{OSINT_RECON_SUCCESS}',
  },
  {
    id: 'osint-003',
    title: 'Domain Intelligence',
    category: 'OSINT',
    difficulty: CYBER_DIFFICULTY.EASY,
    points: 150,
    estimatedMinutes: 25,
    tags: ['osint', 'domain', 'whois'],
    shortDescription: 'Соберите информацию о домене через публичные источники.',
    story: 'Нужно найти информацию о владельце домена и связанных ресурсах.',
    objective: 'Найти регистрационные данные и связанные домены.',
    hint: 'Используйте WHOIS, DNS-записи, сервисы типа Shodan.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{DOMAIN_INTEL_FOUND}',
  },
  {
    id: 'osint-004',
    title: 'GitHub Leak',
    category: 'OSINT',
    difficulty: CYBER_DIFFICULTY.MEDIUM,
    points: 300,
    estimatedMinutes: 45,
    tags: ['osint', 'github', 'leak'],
    shortDescription: 'Найдите утёкшие секреты в публичных репозиториях.',
    story: 'Разработчик случайно закоммитил секреты в публичный репозиторий.',
    objective: 'Найти API-ключи или пароли в истории коммитов.',
    hint: 'Используйте GitHub Search или инструменты типа gitleaks.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{GITHUB_SECRET_LEAK}',
  },

  // Pwn / Binary Exploitation
  {
    id: 'pwn-001',
    title: 'Binary Buffet',
    category: 'Pwn',
    difficulty: CYBER_DIFFICULTY.HARD,
    points: 350,
    estimatedMinutes: 60,
    tags: ['binary', 'overflow'],
    shortDescription: 'Классика: переполнение буфера в учебной программе.',
    story: 'Это учебная задача, но на демо выглядит солидно.',
    objective: 'Смоделировать атаку и "получить shell".',
    hint: 'EIP/RIP любит "A".',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{STACK_SMASHING_DEMO}',
  },
  {
    id: 'pwn-002',
    title: 'Format String Exploit',
    category: 'Pwn',
    difficulty: CYBER_DIFFICULTY.HARD,
    points: 450,
    estimatedMinutes: 70,
    tags: ['format-string', 'exploit', 'binary'],
    shortDescription: 'Эксплуатация уязвимости форматной строки.',
    story: 'Программа использует printf с пользовательским вводом без валидации.',
    objective: 'Использовать format string для чтения/записи памяти.',
    hint: 'Используйте %x, %s, %n для чтения и записи памяти.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{FORMAT_STRING_EXPLOIT}',
  },
  {
    id: 'pwn-003',
    title: 'ROP Chain',
    category: 'Pwn',
    difficulty: CYBER_DIFFICULTY.HARD,
    points: 500,
    estimatedMinutes: 80,
    tags: ['rop', 'chain', 'bypass'],
    shortDescription: 'Обход DEP/ASLR через ROP-цепочку.',
    story: 'Программа защищена DEP и ASLR. Используйте ROP для обхода.',
    objective: 'Построить ROP-цепочку для выполнения shellcode.',
    hint: 'Используйте существующие гаджеты в коде для построения цепочки.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{ROP_CHAIN_SUCCESS}',
  },
  {
    id: 'pwn-004',
    title: 'Heap Overflow',
    category: 'Pwn',
    difficulty: CYBER_DIFFICULTY.HARD,
    points: 480,
    estimatedMinutes: 75,
    tags: ['heap', 'overflow', 'exploit'],
    shortDescription: 'Эксплуатация переполнения кучи для получения контроля.',
    story: 'Программа уязвима к переполнению кучи. Найдите способ эксплуатации.',
    objective: 'Использовать переполнение кучи для выполнения произвольного кода.',
    hint: 'Изучите структуру кучи и механизмы управления памятью.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{HEAP_OVERFLOW_EXPLOIT}',
  },

  // Reverse Engineering
  {
    id: 'rev-001',
    title: 'Crack Me',
    category: 'Reverse',
    difficulty: CYBER_DIFFICULTY.MEDIUM,
    points: 300,
    estimatedMinutes: 50,
    tags: ['reverse', 'crack', 'keygen'],
    shortDescription: 'Взлом защищённой программы для получения ключа.',
    story: 'Программа требует лицензионный ключ. Найдите способ обхода.',
    objective: 'Найти или сгенерировать валидный ключ активации.',
    hint: 'Используйте IDA Pro, Ghidra или x64dbg для анализа.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{CRACK_ME_SOLVED}',
  },
  {
    id: 'rev-002',
    title: 'Obfuscated Code',
    category: 'Reverse',
    difficulty: CYBER_DIFFICULTY.HARD,
    points: 450,
    estimatedMinutes: 70,
    tags: ['reverse', 'obfuscation', 'analysis'],
    shortDescription: 'Анализ обфусцированного кода для поиска флага.',
    story: 'Код защищён обфускацией. Декомпилируйте и найдите секрет.',
    objective: 'Разобрать обфусцированный код и извлечь флаг.',
    hint: 'Используйте статический и динамический анализ.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{OBFUSCATION_DEFEATED}',
  },
  {
    id: 'rev-003',
    title: 'Android APK Analysis',
    category: 'Reverse',
    difficulty: CYBER_DIFFICULTY.MEDIUM,
    points: 320,
    estimatedMinutes: 55,
    tags: ['reverse', 'android', 'apk'],
    shortDescription: 'Анализ Android-приложения для поиска уязвимостей.',
    story: 'Мобильное приложение содержит скрытую функциональность.',
    objective: 'Декомпилировать APK и найти секретный ключ.',
    hint: 'Используйте jadx, apktool или Android Studio для анализа.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{APK_ANALYSIS_DONE}',
  },

  // Network Security
  {
    id: 'net-001',
    title: 'Port Scanning',
    category: 'Network',
    difficulty: CYBER_DIFFICULTY.EASY,
    points: 100,
    estimatedMinutes: 15,
    tags: ['network', 'scanning', 'recon'],
    shortDescription: 'Сканирование портов для поиска открытых сервисов.',
    story: 'Нужно найти открытые порты и определить запущенные сервисы.',
    objective: 'Просканировать сеть и найти уязвимый сервис.',
    hint: 'Используйте nmap для сканирования портов и определения версий.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{PORT_SCAN_COMPLETE}',
  },
  {
    id: 'net-002',
    title: 'Man-in-the-Middle',
    category: 'Network',
    difficulty: CYBER_DIFFICULTY.MEDIUM,
    points: 350,
    estimatedMinutes: 60,
    tags: ['network', 'mitm', 'arp'],
    shortDescription: 'Атака "человек посередине" для перехвата трафика.',
    story: 'Перехватите трафик между клиентом и сервером.',
    objective: 'Выполнить ARP-спуфинг и перехватить данные.',
    hint: 'Используйте arpspoof и Wireshark для перехвата.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{MITM_SUCCESS}',
  },
  {
    id: 'net-003',
    title: 'DNS Tunneling',
    category: 'Network',
    difficulty: CYBER_DIFFICULTY.HARD,
    points: 400,
    estimatedMinutes: 65,
    tags: ['network', 'dns', 'tunneling'],
    shortDescription: 'Использование DNS-туннелирования для обхода фильтров.',
    story: 'Сеть блокирует HTTP-трафик, но DNS разрешён. Используйте туннель.',
    objective: 'Создать DNS-туннель для передачи данных.',
    hint: 'Используйте инструменты типа dns2tcp или iodine.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{DNS_TUNNEL_ACTIVE}',
  },

  // Mobile Security
  {
    id: 'mob-001',
    title: 'iOS App Analysis',
    category: 'Mobile',
    difficulty: CYBER_DIFFICULTY.MEDIUM,
    points: 300,
    estimatedMinutes: 50,
    tags: ['mobile', 'ios', 'analysis'],
    shortDescription: 'Анализ iOS-приложения для поиска уязвимостей.',
    story: 'iOS-приложение содержит скрытые функции и секреты.',
    objective: 'Декомпилировать IPA и найти флаг.',
    hint: 'Используйте class-dump, Hopper или Frida для анализа.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{IOS_APP_ANALYZED}',
  },
  {
    id: 'mob-002',
    title: 'Android Root Detection Bypass',
    category: 'Mobile',
    difficulty: CYBER_DIFFICULTY.MEDIUM,
    points: 280,
    estimatedMinutes: 45,
    tags: ['mobile', 'android', 'root'],
    shortDescription: 'Обход проверки root на Android-устройстве.',
    story: 'Приложение блокирует работу на рутованных устройствах.',
    objective: 'Обойти проверку root и запустить приложение.',
    hint: 'Используйте Xposed или Frida для перехвата проверок.',
    flagFormat: 'FLAG{...}',
    demoFlag: 'FLAG{ROOT_DETECTION_BYPASS}',
  },
]

export const labs = [
  {
    id: 'lab-phishing',
    title: 'Anti-Phishing Lab',
    level: 'Beginner',
    durationMinutes: 30,
    description: 'Симуляция анализа фишингового письма: признаки, заголовки, домены.',
    skills: ['Email analysis', 'Headers', 'Domain reputation'],
    checklist: [
      'Проверить домен отправителя',
      'Посмотреть DKIM/SPF/DMARC',
      'Оценить ссылки (hover) и редиректы',
      'Проверить вложения и расширения',
      'Сформировать вывод и рекомендации',
    ],
  },
  {
    id: 'lab-passwords',
    title: 'Password Policy Hardening',
    level: 'Intermediate',
    durationMinutes: 35,
    description: 'Соберите политику паролей и MFA как для корпоративного продукта.',
    skills: ['MFA', 'Policy', 'Risk'],
    checklist: [
      'Определить минимальную длину и сложность',
      'Добавить MFA и резервные коды',
      'Включить защиту от перебора',
      'Настроить восстановление аккаунта',
      'Сформировать чек-лист для аудитора',
    ],
  },
  {
    id: 'lab-web',
    title: 'Web Security Quick Audit',
    level: 'Advanced',
    durationMinutes: 45,
    description: 'Мини-аудит UI/приложения: XSS, CSRF, cookie flags, headers.',
    skills: ['XSS', 'CSRF', 'Security headers'],
    checklist: [
      'Проверить CSP и Security Headers',
      'Проверить cookie (HttpOnly/SameSite/Secure)',
      'Проверить формы на CSRF',
      'Проверить пользовательский ввод (XSS)',
      'Составить краткий отчёт',
    ],
  },
  {
    id: 'lab-penetration',
    title: 'Penetration Testing Basics',
    level: 'Intermediate',
    durationMinutes: 60,
    description: 'Полный цикл пентеста: разведка, сканирование, эксплуатация, отчёт.',
    skills: ['Recon', 'Scanning', 'Exploitation', 'Reporting'],
    checklist: [
      'Провести разведку (OSINT)',
      'Сканировать сеть и порты',
      'Идентифицировать уязвимости',
      'Эксплуатировать найденные уязвимости',
      'Составить отчёт с рекомендациями',
    ],
  },
  {
    id: 'lab-incident',
    title: 'Incident Response Simulation',
    level: 'Advanced',
    durationMinutes: 90,
    description: 'Симуляция инцидента безопасности: обнаружение, анализ, реагирование.',
    skills: ['Incident Response', 'Forensics', 'Containment'],
    checklist: [
      'Обнаружить индикаторы компрометации',
      'Собрать и проанализировать логи',
      'Определить вектор атаки',
      'Применить меры сдерживания',
      'Составить отчёт об инциденте',
    ],
  },
  {
    id: 'lab-malware',
    title: 'Malware Analysis Basics',
    level: 'Advanced',
    durationMinutes: 75,
    description: 'Статический и динамический анализ вредоносного ПО.',
    skills: ['Malware Analysis', 'Reverse Engineering', 'Sandbox'],
    checklist: [
      'Провести статический анализ',
      'Использовать sandbox для динамического анализа',
      'Идентифицировать поведение и функции',
      'Извлечь индикаторы компрометации (IOC)',
      'Составить профиль угрозы',
    ],
  },
  {
    id: 'lab-network',
    title: 'Network Security Assessment',
    level: 'Intermediate',
    durationMinutes: 50,
    description: 'Оценка безопасности сетевой инфраструктуры.',
    skills: ['Network Security', 'Firewall', 'IDS/IPS'],
    checklist: [
      'Проанализировать конфигурацию firewall',
      'Проверить правила IDS/IPS',
      'Оценить сегментацию сети',
      'Проверить шифрование трафика',
      'Составить план улучшений',
    ],
  },
  {
    id: 'lab-cloud',
    title: 'Cloud Security Audit',
    level: 'Advanced',
    durationMinutes: 80,
    description: 'Аудит безопасности облачной инфраструктуры (AWS/Azure/GCP).',
    skills: ['Cloud Security', 'IAM', 'Compliance'],
    checklist: [
      'Проверить конфигурацию IAM',
      'Оценить политики доступа',
      'Проверить шифрование данных',
      'Оценить соответствие стандартам',
      'Составить отчёт с рекомендациями',
    ],
  },
]

export const cyberTools = [
  {
    id: 'tool-nmap',
    name: 'Nmap',
    category: 'Scanning',
    description: 'Сканер портов и сервисов для сетевой разведки.',
    tags: ['network', 'recon', 'scanning'],
  },
  {
    id: 'tool-burp',
    name: 'Burp Suite',
    category: 'Web Testing',
    description: 'Прокси и набор инструментов для тестирования веб-приложений.',
    tags: ['web', 'proxy', 'testing'],
  },
  {
    id: 'tool-wireshark',
    name: 'Wireshark',
    category: 'Forensics',
    description: 'Анализ трафика и разбор сетевых дампов.',
    tags: ['pcap', 'analysis', 'network'],
  },
  {
    id: 'tool-snyk',
    name: 'Snyk',
    category: 'Dependencies',
    description: 'Поиск уязвимостей в зависимостях и контейнерах.',
    tags: ['supply-chain', 'sca', 'vulnerabilities'],
  },
  {
    id: 'tool-cheatsheets',
    name: 'OWASP Cheat Sheets',
    category: 'Reference',
    description: 'Шпаргалки: OWASP Top 10, JWT, CSP, SQLi, XSS.',
    tags: ['owasp', 'reference', 'security'],
  },
  {
    id: 'tool-metasploit',
    name: 'Metasploit Framework',
    category: 'Exploitation',
    description: 'Фреймворк для разработки и выполнения эксплойтов.',
    tags: ['exploitation', 'framework', 'pentest'],
  },
  {
    id: 'tool-sqlmap',
    name: 'SQLMap',
    category: 'Web Testing',
    description: 'Автоматизированное обнаружение и эксплуатация SQL-инъекций.',
    tags: ['sql', 'injection', 'automation'],
  },
  {
    id: 'tool-ghidra',
    name: 'Ghidra',
    category: 'Reverse Engineering',
    description: 'Инструмент для обратной инженерии от NSA.',
    tags: ['reverse', 'decompiler', 'analysis'],
  },
  {
    id: 'tool-volatility',
    name: 'Volatility Framework',
    category: 'Forensics',
    description: 'Фреймворк для анализа дампов памяти.',
    tags: ['memory', 'forensics', 'analysis'],
  },
  {
    id: 'tool-john',
    name: 'John the Ripper',
    category: 'Password Cracking',
    description: 'Инструмент для взлома паролей методом перебора.',
    tags: ['password', 'cracking', 'bruteforce'],
  },
  {
    id: 'tool-hashcat',
    name: 'Hashcat',
    category: 'Password Cracking',
    description: 'Быстрый инструмент для восстановления паролей.',
    tags: ['password', 'cracking', 'gpu'],
  },
  {
    id: 'tool-ida',
    name: 'IDA Pro',
    category: 'Reverse Engineering',
    description: 'Интерактивный дизассемблер и отладчик.',
    tags: ['reverse', 'disassembler', 'debugger'],
  },
  {
    id: 'tool-shodan',
    name: 'Shodan',
    category: 'OSINT',
    description: 'Поисковая система для интернет-подключённых устройств.',
    tags: ['osint', 'search', 'iot'],
  },
  {
    id: 'tool-owasp-zap',
    name: 'OWASP ZAP',
    category: 'Web Testing',
    description: 'Автоматизированный сканер безопасности веб-приложений.',
    tags: ['web', 'scanning', 'owasp'],
  },
  {
    id: 'tool-frida',
    name: 'Frida',
    category: 'Dynamic Analysis',
    description: 'Инструмент для динамического анализа приложений.',
    tags: ['dynamic', 'analysis', 'hook'],
  },
  {
    id: 'tool-cobalt',
    name: 'Cobalt Strike',
    category: 'Red Team',
    description: 'Платформа для симуляции продвинутых атак.',
    tags: ['red-team', 'c2', 'simulation'],
  },
  {
    id: 'tool-elastic',
    name: 'Elastic Security',
    category: 'SIEM',
    description: 'Платформа для обнаружения и реагирования на угрозы.',
    tags: ['siem', 'detection', 'response'],
  },
  {
    id: 'tool-splunk',
    name: 'Splunk',
    category: 'SIEM',
    description: 'Платформа для анализа данных безопасности.',
    tags: ['siem', 'analytics', 'logging'],
  },
  {
    id: 'tool-veracode',
    name: 'Veracode',
    category: 'SAST',
    description: 'Статический анализ безопасности кода.',
    tags: ['sast', 'code-analysis', 'security'],
  },
  {
    id: 'tool-checkmarx',
    name: 'Checkmarx',
    category: 'SAST',
    description: 'Платформа для анализа безопасности приложений.',
    tags: ['sast', 'code-analysis', 'vulnerabilities'],
  },
]

export const reportTemplates = [
  {
    id: 'tmpl-quick',
    name: 'Quick Security Report',
    sections: ['Сводка', 'Найденные риски', 'Рекомендации', 'Следующие шаги'],
  },
  {
    id: 'tmpl-ctf',
    name: 'CTF Writeup',
    sections: ['Описание', 'Гипотеза', 'Эксплуатация', 'Фикс', 'Уроки'],
  },
  {
    id: 'tmpl-audit',
    name: 'Web Audit (Lite)',
    sections: ['Scope', 'Методология', 'Находки', 'Severity', 'Remediation'],
  },
  {
    id: 'tmpl-pentest',
    name: 'Penetration Test Report',
    sections: ['Executive Summary', 'Methodology', 'Findings', 'Risk Assessment', 'Recommendations'],
  },
  {
    id: 'tmpl-incident',
    name: 'Incident Response Report',
    sections: ['Timeline', 'Impact Assessment', 'Root Cause', 'Containment', 'Lessons Learned'],
  },
]

export default {
  CYBER_DIFFICULTY,
  ctfChallenges,
  labs,
  cyberTools,
  reportTemplates,
}
